name: Deploy my latest version

on: 
  push: # What triggers a deployment. For example, `push`.
    branches:
      - main # What branch triggers a deployment. For example, `main`.   

jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.5.7'
          kustomize_build_dir: '/borealis-demo/thirdParty/locust'
          kustomize_comment: true
          kustomize_output_file: "/borealis-demo/thirdParty/locust/generatedManifest.yml"
          kustomize_build_options: "--enable-helm"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
          clientSecret:  "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/deploy.yml" # Path to the deployment file. For more information, see the Create a deployment file section.
          #path-to-file: "/deploy-webhook.yml" # Path to the deployment file. For more information, see the Create a deployment file section.
          addContext: "environment2=prod,pr=test"
          applicationName: "potato-facts4sa" # yes?
      #- name: Wait for integration tests to succeed with builtin timeout
      #  uses: fountainhead/action-wait-for-check@v1.0.0
      #  id: wait-for-build
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    checkName: 'Integration_Tests'
      #    ref: ${{ github.ref }}
      #    timeoutSeconds: 600

